[package]
name = "dotafts-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15.0"
glob = "0.3.1"
pulldown-cmark = "0.11.0"
env_logger = "0.11.3"
log = "0.4.21"
